### ISSUE TITLE
Bluetooth Keyboard Arrow Keys/ESC/CTRL

### ISSUE THREAD

**Issue by heroclix** [Code-Hex/White-MobileTerminal#2]
Hi, I am using WhiteTerminal on a Jailbroken iPad Air ios 8.1.2.
I can't seem to use the arrow keys/esc/ctrl keys of my bluetooth keyboard (Apple Bluetooth Keyboard). 
Is there any workaround or plan for a fix? thanks

**Comment by Code-Hex** [comment]
Thanks for using whiteterminal.
It's good idea. 
but I busy now X(
So, I will work from February to it.

Thanks to offer ideas.

**Comment by Code-Hex** [comment]
I'm sorry to be late.
Bluetooth keyboard is supported.
Please wait to look forward to.
