### ISSUE TITLE
Doesn't works on iOS9

### ISSUE THREAD

**Issue by radare** [Code-Hex/White-MobileTerminal#6]
The app closes when launching it

**Comment by radare** [comment]
Another Terminal app fails with this error, which can be related.
![814501685_10448109215165439732](https://cloud.githubusercontent.com/assets/917142/10519839/c19ceb80-7367-11e5-9b9b-6c6e7f334d15.jpg)

**Comment by razum2um** [comment]
same error on 5s (A7 processor) with 9.0.2jb - same crash on start
p.s. screen taken from MTerminal - I have the same error as well.

**Comment by Code-Hex** [comment]
Maybe, rootless is the cause...
Just moment please.

**Comment by khapota** [comment]
I think it is because build option. More detail: http://iphonedevwiki.net/index.php/Updating_extensions_for_iOS_9. wget and curl do not work (curl just updated today)

**Comment by razum2um** [comment]
want to mention, that I have also 4s (A5 processor) and ipad3 (A5X processor) with 9.0.2jb and they both have working WhiteTerminal and no problem with other terminals. (based on the photo of front cam I guess @radare has also iphone5 or higher)

**Comment by radare** [comment]
Maybe a cydia pkg not installed?

**Comment by khapota** [comment]
It is normal with 32bit device.

**Comment by radare** [comment]
Any update on this?

**Comment by radare** [comment]
It turned out to be a bug in the Pangu jailbreak. Upgrading it from Cydia works fine.

**Comment by Code-Hex** [comment]
It's fine!!
And i'm working new terminal project now...

**Comment by radare** [comment]
Why not enhace the current one?

**Comment by Code-Hex** [comment]
The current code is written in the old form of Objective-C. So each time the firemware is updated, it must also rewrite the current code.
The amount of code is also shorter than it is because those who were supported by code that can respond to quickly update is accustomed to everyone happy.

**Comment by radare** [comment]
Swift rewrite? :D

**Comment by Code-Hex** [comment]
Sure.

**Comment by radare** [comment]
That sounds awesome. Also, do you think it would be possible to use thise new terminal code as an embedded widget in 3rd party apps?
